ARG RUBY_VERSION
FROM --platform=linux/amd64 ruby:${RUBY_VERSION}-slim

ENV NODE_ENV="production" \
  RAILS_ENV="production" \
  BUNDLE_DEPLOYMENT="1" \
  BUNDLE_PATH="/usr/local/bundle" \
  BUNDLE_WITHOUT="development"

# Install dependencies
RUN apt-get update -qq && \
  apt-get install --no-install-recommends -y \
  curl build-essential zlib1g-dev git libpq-dev \
  # Editor
  vim nano \
  # For nvm and Node.js
  libffi-dev python python-is-python2 \
  # For mimemagic gem
  shared-mime-info \
  # Clean up
  && rm -rf /var/lib/apt/lists/*

# Install Ruby bundler
RUN bash -c "gem install bundler -v '1.17.3'"

# Leonardo: I tried installing via apt-get using the source (https://deb.nodesource.com/setup_10.x),
# but it ended up installing version 12.
# Install Node.js 10.24.1 manually
RUN curl -fsSL https://nodejs.org/dist/v10.24.1/node-v10.24.1-linux-x64.tar.xz \
  | tar -xJ -C /usr/local --strip-components=1

# Install Yarn globally using npm
RUN npm install -g yarn

# Rails app lives here
WORKDIR /rails

# Install application gems
COPY Gemfile Gemfile.lock package.json yarn.lock ./
RUN bundle install && \
  yarn install --frozen-lockfile

# Copy application code
COPY . .

# Precompiling assets for production
# TODO: need to change when upgrade Rails.
RUN SECRET_KEY_BASE=dummy ./bin/rails assets:precompile

# Run and own only the runtime files as a non-root user for security
RUN groupadd --system --gid 1000 rails && \
  useradd rails --uid 1000 --gid 1000 --create-home --shell /bin/bash && \
  chown -R rails:rails db log tmp
USER 1000:1000

# Entrypoint prepares the database.
ENTRYPOINT ["/rails/bin/docker-entrypoint"]

EXPOSE 80
CMD ["./bin/rails", "server"]
