# No ghcr.io/ prefix — Kamal prepends localhost:5555/ from config/deploy.yml
image: unepwcmc/cites-compliance-tool/rails-staging

servers:
  web:
    hosts:
      - 172.20.0.146
    options:
      add-host: host.docker.internal:host-gateway
    proxy:
      hosts:
        - cites-compliance-tool-sapi-web-staging-01.internal.unep-wcmc.org
      ssl:
        certificate_pem: CERTIFICATE_PEM
        private_key_pem: PRIVATE_KEY_PEM
      forward_headers: true # Forward headers like X-Forwarded-Proto
      logging:
        request_headers:
          - Cache-Control
          - User-Agent
          - X-Forwarded-Proto
        response_headers:
          - X-Request-ID

env:
  clear:
    RAILS_ENV: staging
    SPECIES_API_URL: https://staging.speciesplus.net/api/v1
    CERTIFICATE_PATH: ""
    MAILER_HOST: https://cites-compliance-tool-sapi-web-staging-01.internal.unep-wcmc.org
